import { NextResponse } from 'next/server';

export default function handler(req, res) {
  const lgErr = [
    {
      error: {
        status: 405,
        name: 'ForbiddenError',
        message: 'Forbidden',
      },
    },
  ];
  if (req?.method !== 'GET') {
    return res?.status(405).json(lgErr);
  }
  const rslt = {
    data: [
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-1.svg',
        captions: '1',
        mobileSizeUp: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-2.svg',
        captions: '2',
        mobileSizeUp: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-3.svg',
        captions: '3',
        mobileSizeUp: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-4.svg',
        captions: '4',
        mobileSizeUp: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-5.svg',
        captions: '5',
        mobileSizeUp: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-6.svg',
        captions: '6',
        mobileSizeUp: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-7.svg',
        captions: '7',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-8.svg',
        captions: '8',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-9.svg',
        captions: '9',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-10.svg',
        captions: '10',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-11.svg',
        captions: '11',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-12.svg',
        captions: '12',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-13.svg',
        captions: '13',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-14.svg',
        captions: '14',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-15.svg',
        captions: '15',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-16.svg',
        captions: '16',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-17.svg',
        captions: '17',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-18.svg',
        captions: '18',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-19.svg',
        captions: '19',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-20.png',
        captions: '20',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-21.svg',
        captions: '21',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-22.svg',
        captions: '22',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-23.svg',
        captions: '23',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-24.png',
        captions: '24',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-25.svg',
        captions: '25',
        mobileSizeUp: false,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-26.png',
        captions: '26',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-27.svg',
        captions: '27',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-28.svg',
        captions: '28',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-29.svg',
        captions: '29',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-30.png',
        captions: '30',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-31.png',
        captions: '31',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-32.svg',
        captions: '32',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-33.png',
        captions: '33',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-34.svg',
        captions: '34',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-35.svg',
        captions: '35',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-36.png',
        captions: '36',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-37.svg',
        captions: '37',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-38.svg',
        captions: '38',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-39.png',
        captions: '39',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
      {
        url: '/',
        images: '/assets/images/partners/ca25Partner-40.svg',
        captions: '40',
        mobileSizeUp: false,
        mobileReduce: true,
        openUrl: false,
      },
    ],
  };
  res?.status(200).json(rslt);
}
